; Listing generated by Microsoft (R) Optimizing Compiler Version 19.32.31332.0 

	TITLE	C:\Users\23035\Desktop\Home\C++\AddShell\shellcode\main.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_entry
EXTRN	??0kernel@@QAE@XZ:PROC				; kernel::kernel
EXTRN	??0msvc@@QAE@PAUkernel@@@Z:PROC			; msvc::msvc
; Function compile flags: /Ogspy
;	COMDAT _entry
_TEXT	SEGMENT
_msvc$ = -68						; size = 44
_kernel$ = -24						; size = 12
_str$ = -12						; size = 11
_entry	PROC						; COMDAT
; File C:\Users\23035\Desktop\Home\C++\AddShell\shellcode\main.cpp
; Line 4
	push	ebp
	mov	ebp, esp
	sub	esp, 68					; 00000044H
; Line 5
	lea	ecx, DWORD PTR _kernel$[ebp]
	call	??0kernel@@QAE@XZ			; kernel::kernel
; Line 6
	lea	eax, DWORD PTR _kernel$[ebp]
	push	eax
	lea	ecx, DWORD PTR _msvc$[ebp]
	call	??0msvc@@QAE@PAUkernel@@@Z		; msvc::msvc
; Line 8
	lea	eax, DWORD PTR _str$[ebp]
	mov	DWORD PTR _str$[ebp], 1819043176	; 6c6c6568H
	push	eax
	mov	DWORD PTR _str$[ebp+4], 1919907695	; 726f776fH
	mov	WORD PTR _str$[ebp+8], 25708		; 0000646cH
	mov	BYTE PTR _str$[ebp+10], 0
	call	DWORD PTR _msvc$[ebp]
	pop	ecx
; Line 9
	xor	eax, eax
; Line 10
	leave
	ret	0
_entry	ENDP
_TEXT	ENDS
END
